/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Metadata for the EPUB document. */
export interface EpubInfo {
  title: string
  description: string
  publisher: string
  author: string
  /** Label used for the Table of Contents page. */
  tocTitle: string
  lang: string
  fonts: Array<string>
  /** Raw CSS string injected as `styles.css`. Pass `null` for an empty stylesheet. */
  css?: string
  /** EPUB spec version (use `3`). */
  version: number
  /** Raw XML written to `META-INF/encryption.xml`. Pass `null` to omit. */
  encryption?: string
  /** Raw XML written to `META-INF/metadata.xml`. Pass `null` to omit. */
  metadataXml?: string
  /** Raw XML written to `META-INF/manifest.xml`. Pass `null` to omit. */
  manifestXml?: string
}
/**
 * An image embedded in the EPUB.
 *
 * Images are written to `OEBPS/images/<path>` and can be referenced from
 * chapter paragraphs with raw markup, e.g.
 * `<img src="images/diagram.png" alt="Diagram" />`.
 */
export interface EpubImage {
  /** Unique manifest id (letters, digits, `-`, `_`). */
  id: string
  /**
   * File name written under `OEBPS/images/`, e.g. `cover.png`.
   * The extension determines the media-type.
   */
  path: string
  /** Raw image bytes. */
  data: Buffer
  /** When `true`, this image is the book cover (at most one). */
  cover: boolean
}
/**
 * EPUB builder.
 *
 * Each chapter is an array of strings: index 0 is the chapter title,
 * subsequent entries become `<p>` elements in the chapter body.
 *
 * ```js
 * const epub = new Epub(info, [
 *   ['Chapter One', 'First paragraph.', 'Second paragraph.'],
 * ]);
 * epub.setImages([
 *   { id: 'cover-img', path: 'cover.png', data: coverBytes, cover: true },
 * ]);
 * ```
 */
export declare class Epub {
  /** Create a new EPUB builder. */
  constructor(info: EpubInfo, chapters: Array<Array<string>>)
  /**
   * Attach images to the EPUB. Pass an array of `EpubImage` objects.
   * Flag exactly one with `cover: true` to set the book cover.
   */
  setImages(images: Array<EpubImage>): void
  /** Build the EPUB and write it to `<title>.epub` in the current working directory. */
  run(): void
  /**
   * Build the EPUB and return its contents as a `Buffer`.
   * Useful when you want to stream, upload, or write the file yourself.
   *
   * ```js
   * const buf = epub.archive();
   * fs.writeFileSync('my-book.epub', buf);
   * ```
   */
  archive(): Buffer
}
