/* Auto-generated by napi-rs — do not edit by hand */

/** Metadata for the EPUB document. */
export interface EpubInfo {
  title: string
  description: string
  publisher: string
  author: string
  /** Label used for the Table of Contents page. */
  tocTitle: string
  lang: string
  fonts: string[]
  /** Raw CSS string injected as `styles.css`. Pass `null` for an empty stylesheet. */
  css?: string | null
  /** EPUB spec version (use `3`). */
  version: number
}

/**
 * EPUB builder.
 *
 * Each chapter is an array of strings: index 0 is the chapter title,
 * subsequent entries become `<p>` elements in the chapter body.
 *
 * @example
 * ```js
 * const epub = new Epub(info, [
 *   ['Chapter One', 'First paragraph.', 'Second paragraph.'],
 * ]);
 * ```
 */
export class Epub {
  /**
   * Create a new EPUB builder.
   * @param info - Document metadata.
   * @param chapters - Array of chapters. Each chapter is `[title, ...paragraphs]`.
   */
  constructor(info: EpubInfo, chapters: string[][])

  /**
   * Build the EPUB and write it to `<title>.epub` in the current working directory.
   */
  run(): void

  /**
   * Build the EPUB and return its contents as a `Buffer`.
   * Useful when you want to stream, upload, or write the file yourself.
   *
   * @example
   * ```js
   * const buf = epub.archive();
   * fs.writeFileSync('my-book.epub', buf);
   * ```
   */
  archive(): Buffer
}
