/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Metadata for the EPUB document. */
export interface EpubInfo {
  title: string
  description: string
  publisher: string
  author: string
  /** Label used for the Table of Contents page. */
  tocTitle: string
  lang: string
  fonts: Array<string>
  /** Raw CSS string injected as `styles.css`. Pass `null` for an empty stylesheet. */
  css?: string
  /** EPUB spec version (use `3`). */
  version: number
}
/**
 * EPUB builder.
 *
 * Each chapter is an array of strings: index 0 is the chapter title,
 * subsequent entries become `<p>` elements in the chapter body.
 *
 * ```js
 * const epub = new Epub(info, [
 *   ['Chapter One', 'First paragraph.', 'Second paragraph.'],
 * ]);
 * ```
 */
export declare class Epub {
  /** Create a new EPUB builder. */
  constructor(info: EpubInfo, chapters: Array<Array<string>>)
  /** Build the EPUB and write it to `<title>.epub` in the current working directory. */
  run(): void
  /**
   * Build the EPUB and return its contents as a `Buffer`.
   * Useful when you want to stream, upload, or write the file yourself.
   *
   * ```js
   * const buf = epub.archive();
   * fs.writeFileSync('my-book.epub', buf);
   * ```
   */
  archive(): Buffer
}
